powerconsumption <- read.table("household_power_consumption.txt",sep=";", na.strings="?",header=T)
subsetpower <- powerconsumption[powerconsumption$Date %in% c("1/2/2007", "2/2/2007"), ]
alldays<-strptime(paste(subsetpower$Date, subsetpower$Time), "%d/%m/%Y %H:%M:%S")
png("plot3.png", width = 480, height = 480)
plot(alldays, subsetpower$Sub_metering_1, type="n", ylab="Energy sub metering", xlab="")
lines(alldays, subsetpower$Sub_metering_1, type="l", col="black")
lines(alldays, subsetpower$Sub_metering_2, type="l", col="red")
lines(alldays, subsetpower$Sub_metering_3, type="l", col="blue")
legend("topright", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty=c(1,1,1), col=c("black", "red", "blue"))
dev.off()
