powerconsumption <- read.table("household_power_consumption.txt",sep=";", na.strings="?",header=T)
subsetpower <- powerconsumption[powerconsumption$Date %in% c("1/2/2007", "2/2/2007"), ]
alldays<-strptime(paste(subsetpower$Date, subsetpower$Time), "%d/%m/%Y %H:%M:%S")
png("plot4.png", width = 480, height = 480)
par(mfrow= c(2,2))
plot(alldays,subsetpower$Global_active_power, type="l", ylab="Global Active Power",xlab="")
plot(alldays,subsetpower$Voltage, type="l", ylab="Voltage",xlab="datetime")
plot(alldays,subsetpower$Sub_metering_1,type="l", main="", xlab="", ylab="Energy sub metering", col="black")
lines(alldays,subsetpower$Sub_metering_2, type="l", col="red")
lines(alldays,subsetpower$Sub_metering_3, type="l", col="blue")
legend("topright", legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), pch= "_", cex=.5,col=c("black","red","blue"))
plot(alldays,subsetpower$Global_reactive_power, type = "l", xlab = "datetime",ylab = "Global_reactive_power")
dev.off()